#                                    _Assignment on Numpy_

In [2]:
import numpy as np

# 1 a. Create the given array

In [144]:
values_a = np.arange(1,101).reshape(10,10) 

In [146]:
values_a / 100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

#### 1 b.  Create an array of 20 linearly spaced points between 0 and 1

In [148]:
linearly_spaced = np.linspace(0,1,20)
linearly_spaced

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

# 2 : Creating the MAT

In [6]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [38]:
#1.C
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [9]:
#1.D
mat[3][4]

20

In [18]:
#1.E
mat[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [21]:
#1.f
mat[4]

array([21, 22, 23, 24, 25])

In [23]:
#1.g
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

##### 2. Following is the 2-D array

In [152]:
import numpy
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]])


In [153]:
sampleArray

array([[34, 43, 73],
       [82, 22, 12],
       [53, 94, 66]])

In [154]:
#### Print the max from axis = 0
sampleArray.max(axis=0)

array([82, 94, 73])

In [155]:
#### Print the min from axis = 1
sampleArray.min(axis=1)

array([34, 12, 53])

##### 3rd Question

# Create an 8X3 integer array from a range between 10 to 34 such that the difference between each element is 1 and then Split the array into four equal-sized sub-arrays.

In [125]:
arr_range = np.arange(10, 34, 1).reshape(4,6)
arr_range

array([[10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33]])

# 4th Following is the given numpy array return array of odd rows and even columns

In [126]:
array_odd_even = np.array([[3 ,6, 9, 12], [15 ,18, 21, 24], [27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])

In [127]:
array_odd_even[::2, 1::2]

array([[ 6, 12],
       [30, 36],
       [54, 60]])

# 5th Question:  Given a 6×6 Numpy array arr, write the code to slice the shaded element?

#### A. Creating 6 * 6 array and reshaping them

In [64]:
ar_66 = np.arange(36).reshape(6,6)

In [65]:
ar_66

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

#### B. Finding out the shades

In [77]:
ar_66.diagonal()

array([ 0,  7, 14, 21, 28, 35])

# 6. Given a 6×6 Numpy array arr, write the code to slice the shaded elements ?

In [87]:
ar_66_shaped = np.arange(36).reshape(6,6)

In [88]:
ar_66_shaped

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

#### slice the shaded elements

In [117]:
ar_66_shaped[2:4,2:4]

array([[14, 15],
       [20, 21]])

# 7. Find out the output of the code below

In [113]:
old = np.array([[1,1,1],[1,1,1]])
new = old 
new[0,:2] = 0
print(old)

[[0 0 1]
 [1 1 1]]


#### 8.Find out the output of the code below:


In [114]:
old = np.array([[1,1,1],[1,1,1]])
new = old.copy() 
new[0,:2] = 0
print(old)

[[1 1 1]
 [1 1 1]]


                                            ###### Thank You ################